### ISSUE TITLE
Has two errors with Unity 2020.1.9f1 and DOTween (HOTween v2) 1.2.420

### ISSUE THREAD

**Issue by CarstenGermer** [zephyo/Yarn-Pile#1]
Just wanted to check Yarn-Pile and get two errors after following the installation instructions.

Assets\Third Party\CharTween\Scripts\VertexGradientPlugin.cs(85,30): error CS0115: 'VertexGradientPlugin.SetFrom(TweenerCore<VertexGradient, VertexGradient, NoOptions>, VertexGradient, bool)': no suitable method found to override

Assets\Third Party\CharTween\Scripts\VertexGradientPlugin.cs(14,18): error CS0534: 'VertexGradientPlugin' does not implement inherited abstract member 'ABSTweenPlugin<VertexGradient, VertexGradient, NoOptions>.SetFrom(TweenerCore<VertexGradient, VertexGradient, NoOptions>, VertexGradient, bool, bool)'

That is nothing I can fix offhand... Or does Yarn-Pile need DOTween Pro?

Cheers /Carsten

**Comment by CarstenGermer** [comment]
Quickfix by just changing the parameters of the override with "throw new System.NotImplementedException();" didn't help much.

Choosing the "Main" scene and starting I get 
MissingFieldException: Field with name 'language' does not exist. You can ignore missing fields by setting...
Menus work (nice!) when pressing "Play" I get
DialogueException: Cannot load node Start: No nodes have been loaded.

I has a little sad... ;)

**Comment by zephyo** [comment]
Yes in installation it says Yarn-Pile needs DOTween.

I pushed fix for the MissingFieldException (see https://github.com/YarnSpinnerTool/YarnSpinner-Unity/issues/36)

**Comment by CarstenGermer** [comment]
Thank you.
